[mypy]
python_version = 3.14
plugins = mypy_django_plugin.main
files = core,accounts,contacts,images,organizations,tags,DjangoApiStarter
exclude = (^.*\/migrations\/.*$|^.*\/tests\/.*$|^.*\/__pycache__\/.*$)
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = True
warn_redundant_casts = True
check_untyped_defs = True
disallow_untyped_defs = False

[mypy.plugins.django-stubs]
django_settings_module = DjangoApiStarter.settings.test
