# Generated by Django 6.0.7 on 2026-07-15 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "identity_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
