# Generated by Django 6.0.7 on 2026-07-15 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_harden_registration_and_email_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="pendingemailchange",
            name="token",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="pendingpasswordreset",
            name="token",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="pendingpasswordreset",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="pendingregistration",
            name="token",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
