# Generated by Django 6.0.5 on 2026-07-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to=images.models.image_upload_to)),
                ("description", models.TextField(blank=True, default="")),
                ("alt_text", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_image_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="images.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolymorphicImageRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("custom_description", models.TextField(blank=True, null=True)),
                (
                    "custom_alt_text",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "custom_title",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["organization", "created_at"], name="images_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagesharelink",
            index=models.Index(
                fields=["image", "revoked_at"], name="img_share_image_revoked_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polymorphicimagerelation",
            index=models.Index(
                fields=["content_type", "object_id", "order"], name="rel_obj_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="polymorphicimagerelation",
            constraint=models.UniqueConstraint(
                fields=("image", "content_type", "object_id"),
                name="images_relation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="polymorphicimagerelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("content_type", "object_id", "is_cover"),
                name="uniq_primary_per_object",
            ),
        ),
    ]
