"""
Django settings for DjangoApiStarter project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
import environ
from django.utils.deprecation import RemovedInDjango60Warning

PROJECT_NAME = os.getenv("PROJECT_NAME", "DjangoApiStarter")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Silence deprecation warning from django-ninja re-registering 'uuid' converter (safe to ignore)
warnings.filterwarnings(
    "ignore",
    category=RemovedInDjango60Warning,
    message=r"Converter 'uuid' is already registered\.",
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='keySoS3cr3tOMGomgnoCaps')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=["localhost", "127.0.0.1"])

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# CSP Settings
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': ("'self'", "'unsafe-inline'", "'unsafe-eval'", 'https://cdn.jsdelivr.net'),
        'style-src': ("'self'", "'unsafe-inline'", 'https://cdn.jsdelivr.net'),
        'img-src': ("'self'", "data:", "blob:", 'https://django-ninja.dev'),
        'font-src': ("'self'",),
        'connect-src': ("'self'",),
    }
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.sites",
    "django_extensions",
    "storages",
    "django_filters",
    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.storage",
    "ninja_extra",
    "csp",
    "corsheaders",
    "defender",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "imagekit",
    "django_celery_beat",
    "django_redis",
    "accounts",
    "organizations.apps.OrganizationsConfig",
    "core",
    "contacts",
    "tags",
    "images"
]

MIDDLEWARE = [
    "DjangoApiStarter.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
]

AUTH_USER_MODEL = "accounts.User"

ROOT_URLCONF = "DjangoApiStarter.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoApiStarter.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': env('POSTGRES_DB', default='django_db'),
        'USER': env('POSTGRES_USER', default='django_user'),
        'PASSWORD': env('POSTGRES_PASSWORD', default='django_pass'),
        'HOST': env('POSTGRES_HOST', default='db'),
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}

# Redis Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_URL', default='redis://redis:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = env('REDIS_URL', default='redis://redis:6379/1')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Beat Scheduled Tasks
CELERY_BEAT_SCHEDULE = {
    "cleanup_expired_tokens": {
        "task": "accounts.tasks.cleanup_expired_tokens",
        "schedule": 86400,  # every 24 hours
    },
    # Orphaned tag cleanup (weekly)
    "cleanup_orphaned_tags": {
        "task": "tags.tasks.cleanup_orphaned_tags_task",
        "schedule": 7 * 24 * 60 * 60,  # every 7 days
    },
    # Orphaned image cleanup (weekly)
    "cleanup_orphaned_images": {
        "task": "images.tasks.cleanup_orphaned_images_task",
        "schedule": 7 * 24 * 60 * 60,  # every 7 days
    },
}

# Storage Configuration
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": env('R2_ACCESS_KEY_ID'),
            "secret_key": env('R2_SECRET_ACCESS_KEY'),
            "bucket_name": env('R2_BUCKET_NAME'),
            "endpoint_url": env('R2_ENDPOINT_URL'),
            "region_name": "auto",
            "addressing_style": "virtual",
            "signature_version": "s3v4",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration (structured JSON for audit logs)
LOG_LEVEL = env("LOG_LEVEL", default="INFO")

# Upload constraints
# Max image size in bytes (default 10MB)
UPLOAD_IMAGE_MAX_BYTES = env.int("UPLOAD_IMAGE_MAX_BYTES", default=10 * 1024 * 1024)
# Allowed MIME type prefixes for images (comma-separated env optional)
_UPLOAD_ALLOWED_PREFIXES = env.str("UPLOAD_ALLOWED_IMAGE_MIME_PREFIXES", default="image/")
UPLOAD_ALLOWED_IMAGE_MIME_PREFIXES = tuple(p.strip() for p in _UPLOAD_ALLOWED_PREFIXES.split(",") if p.strip())

# API throttling: enabled by default; individual endpoints may configure per-user rates
NINJA_RATELIMIT_ENABLE = env.bool("NINJA_RATELIMIT_ENABLE", default=True)

# Image API rate limits (per user)
IMAGES_RATE_LIMIT_UPLOAD = env.str("IMAGES_RATE_LIMIT_UPLOAD", default="60/h")
IMAGES_RATE_LIMIT_BULK_UPLOAD = env.str("IMAGES_RATE_LIMIT_BULK_UPLOAD", default="30/h")
IMAGES_RATE_LIMIT_BULK_DELETE = env.str("IMAGES_RATE_LIMIT_BULK_DELETE", default="30/h")
IMAGES_RATE_LIMIT_BULK_ATTACH = env.str("IMAGES_RATE_LIMIT_BULK_ATTACH", default="60/h")
IMAGES_RATE_LIMIT_BULK_DETACH = env.str("IMAGES_RATE_LIMIT_BULK_DETACH", default="60/h")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "core.utils.logging.JSONFormatter",
        },
        "plain": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "stream": "ext://sys.stdout",
            "formatter": "json",
        },
        "console_plain": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "stream": "ext://sys.stdout",
            "formatter": "plain",
        },
    },
    "loggers": {
        # Minimal audit logger used by images/tags APIs
        "audit": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Default Django logger (plain text)
        "django": {
            "handlers": ["console_plain"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
    },
    # Root logger
    "root": {
        "handlers": ["console_plain"],
        "level": LOG_LEVEL,
    },
}
